name: Upload Docker Image

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - base_image: "python:3.11-slim-bullseye"
          tag_suffix: "slim-bullseye"
        - base_image: "registry.astralinux.ru/library/astra/ubi18-python311:1.8"
          tag_suffix: "astra-ubi18-python311"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "version=$(cat VERSION | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}-${{ matrix.tag_suffix }}
          flavor: |
            latest=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max